name: feature
description: feature
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: checkboxes
    attributes:
      label: hoge
      options:
        - label: hoge
